### ISSUE TITLE
Won't allow import of Logging.

### ISSUE THREAD

**Issue by oliviagwynn1** [oliviagwynn1/heart_rate_sentinel_server#3]
I am receiving an error when I try to install the 'logging' package into my environment.

**Comment by mlp6** [comment]
Check to make sure that anaconda has this module installed; if not, then in the Anaconda Command window, try running: `conda install logging`.

**Comment by mlp6** [comment]
Don't worry about this.

**Comment by oliviagwynn1** [comment]
Alright!
